// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pricing-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PriceResponse_Status int32

const (
	PriceResponse_SUCCESS PriceResponse_Status = 0
	PriceResponse_FAIL    PriceResponse_Status = 1
)

var PriceResponse_Status_name = map[int32]string{
	0: "SUCCESS",
	1: "FAIL",
}

var PriceResponse_Status_value = map[string]int32{
	"SUCCESS": 0,
	"FAIL":    1,
}

func (x PriceResponse_Status) String() string {
	return proto.EnumName(PriceResponse_Status_name, int32(x))
}

func (PriceResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_14ca4ba54db569f0, []int{1, 0}
}

type PriceRequest struct {
	Notional                               float64  `protobuf:"fixed64,1,opt,name=notional,proto3" json:"notional,omitempty"`
	InterestYearlyRate                     float64  `protobuf:"fixed64,2,opt,name=interestYearlyRate,proto3" json:"interestYearlyRate,omitempty"`
	InsuranceYearlyRate                    float64  `protobuf:"fixed64,3,opt,name=insuranceYearlyRate,proto3" json:"insuranceYearlyRate,omitempty"`
	DurationYears                          int64    `protobuf:"varint,4,opt,name=durationYears,proto3" json:"durationYears,omitempty"`
	AnticipatedRedemptionPeriod            int64    `protobuf:"varint,5,opt,name=anticipatedRedemptionPeriod,proto3" json:"anticipatedRedemptionPeriod,omitempty"`
	AnticipatedRedemptionAmount            float64  `protobuf:"fixed64,6,opt,name=anticipatedRedemptionAmount,proto3" json:"anticipatedRedemptionAmount,omitempty"`
	AnticipatedRedemptionNewMonthlyPayment float64  `protobuf:"fixed64,7,opt,name=anticipatedRedemptionNewMonthlyPayment,proto3" json:"anticipatedRedemptionNewMonthlyPayment,omitempty"`
	XXX_NoUnkeyedLiteral                   struct{} `json:"-"`
	XXX_unrecognized                       []byte   `json:"-"`
	XXX_sizecache                          int32    `json:"-"`
}

func (m *PriceRequest) Reset()         { *m = PriceRequest{} }
func (m *PriceRequest) String() string { return proto.CompactTextString(m) }
func (*PriceRequest) ProtoMessage()    {}
func (*PriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ca4ba54db569f0, []int{0}
}

func (m *PriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceRequest.Unmarshal(m, b)
}
func (m *PriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceRequest.Marshal(b, m, deterministic)
}
func (m *PriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceRequest.Merge(m, src)
}
func (m *PriceRequest) XXX_Size() int {
	return xxx_messageInfo_PriceRequest.Size(m)
}
func (m *PriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PriceRequest proto.InternalMessageInfo

func (m *PriceRequest) GetNotional() float64 {
	if m != nil {
		return m.Notional
	}
	return 0
}

func (m *PriceRequest) GetInterestYearlyRate() float64 {
	if m != nil {
		return m.InterestYearlyRate
	}
	return 0
}

func (m *PriceRequest) GetInsuranceYearlyRate() float64 {
	if m != nil {
		return m.InsuranceYearlyRate
	}
	return 0
}

func (m *PriceRequest) GetDurationYears() int64 {
	if m != nil {
		return m.DurationYears
	}
	return 0
}

func (m *PriceRequest) GetAnticipatedRedemptionPeriod() int64 {
	if m != nil {
		return m.AnticipatedRedemptionPeriod
	}
	return 0
}

func (m *PriceRequest) GetAnticipatedRedemptionAmount() float64 {
	if m != nil {
		return m.AnticipatedRedemptionAmount
	}
	return 0
}

func (m *PriceRequest) GetAnticipatedRedemptionNewMonthlyPayment() float64 {
	if m != nil {
		return m.AnticipatedRedemptionNewMonthlyPayment
	}
	return 0
}

type PriceResponse struct {
	Status               PriceResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=v1.PriceResponse_Status" json:"status,omitempty"`
	Message              string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PriceResponse) Reset()         { *m = PriceResponse{} }
func (m *PriceResponse) String() string { return proto.CompactTextString(m) }
func (*PriceResponse) ProtoMessage()    {}
func (*PriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ca4ba54db569f0, []int{1}
}

func (m *PriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceResponse.Unmarshal(m, b)
}
func (m *PriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceResponse.Marshal(b, m, deterministic)
}
func (m *PriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceResponse.Merge(m, src)
}
func (m *PriceResponse) XXX_Size() int {
	return xxx_messageInfo_PriceResponse.Size(m)
}
func (m *PriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PriceResponse proto.InternalMessageInfo

func (m *PriceResponse) GetStatus() PriceResponse_Status {
	if m != nil {
		return m.Status
	}
	return PriceResponse_SUCCESS
}

func (m *PriceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("v1.PriceResponse_Status", PriceResponse_Status_name, PriceResponse_Status_value)
	proto.RegisterType((*PriceRequest)(nil), "v1.PriceRequest")
	proto.RegisterType((*PriceResponse)(nil), "v1.PriceResponse")
}

func init() { proto.RegisterFile("pricing-service.proto", fileDescriptor_14ca4ba54db569f0) }

var fileDescriptor_14ca4ba54db569f0 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x5f, 0x4b, 0xeb, 0x30,
	0x18, 0xc6, 0x4f, 0xf7, 0xa7, 0xdb, 0x79, 0xcf, 0xd9, 0x98, 0x11, 0x21, 0xcc, 0x0b, 0xc7, 0x10,
	0xd9, 0x85, 0x16, 0x37, 0xef, 0xc5, 0x31, 0x14, 0x04, 0x95, 0x92, 0xa2, 0xe0, 0x65, 0x6c, 0x5f,
	0x66, 0x60, 0x4d, 0x6a, 0x92, 0x4e, 0x06, 0x7e, 0x06, 0x3f, 0xb3, 0x34, 0x9d, 0xb2, 0xe1, 0x1c,
	0x5e, 0xe6, 0x7d, 0x7e, 0xef, 0x1f, 0xf2, 0x3c, 0xb0, 0x97, 0x69, 0x11, 0x0b, 0x39, 0x3d, 0x31,
	0xa8, 0xe7, 0x22, 0xc6, 0x20, 0xd3, 0xca, 0x2a, 0x52, 0x99, 0x0f, 0xfb, 0xef, 0x55, 0xf8, 0x1f,
	0x6a, 0x11, 0x23, 0xc3, 0x97, 0x1c, 0x8d, 0x25, 0x5d, 0x68, 0x4a, 0x65, 0x85, 0x92, 0x7c, 0x46,
	0xbd, 0x9e, 0x37, 0xf0, 0xd8, 0xd7, 0x9b, 0x04, 0x40, 0x84, 0xb4, 0xa8, 0xd1, 0xd8, 0x47, 0xe4,
	0x7a, 0xb6, 0x60, 0xdc, 0x22, 0xad, 0x38, 0x6a, 0x83, 0x42, 0x4e, 0x61, 0x57, 0x48, 0x93, 0x6b,
	0x2e, 0x63, 0x5c, 0x69, 0xa8, 0xba, 0x86, 0x4d, 0x12, 0x39, 0x84, 0x56, 0x92, 0x6b, 0x5e, 0xec,
	0x2b, 0xaa, 0x86, 0xd6, 0x7a, 0xde, 0xa0, 0xca, 0xd6, 0x8b, 0xe4, 0x02, 0xf6, 0xb9, 0xb4, 0x22,
	0x16, 0x19, 0xb7, 0x98, 0x30, 0x4c, 0x30, 0xcd, 0x0a, 0x35, 0x44, 0x2d, 0x54, 0x42, 0xeb, 0xae,
	0x67, 0x1b, 0xf2, 0xe3, 0x84, 0x71, 0xaa, 0x72, 0x69, 0xa9, 0xef, 0x2e, 0xdc, 0x86, 0x90, 0x07,
	0x38, 0xda, 0x28, 0xdf, 0xe1, 0xeb, 0xad, 0x92, 0xf6, 0x79, 0xb6, 0x08, 0xf9, 0x22, 0x45, 0x69,
	0x69, 0xc3, 0x0d, 0xfb, 0x25, 0xdd, 0x7f, 0x83, 0xd6, 0xd2, 0x0f, 0x93, 0x29, 0x69, 0x8a, 0x4f,
	0xf4, 0x8d, 0xe5, 0x36, 0x37, 0xce, 0x8e, 0xf6, 0x88, 0x06, 0xf3, 0x61, 0xb0, 0x86, 0x04, 0x91,
	0xd3, 0xd9, 0x92, 0x23, 0x14, 0x1a, 0x29, 0x1a, 0xc3, 0xa7, 0xa5, 0x37, 0x7f, 0xd9, 0xe7, 0xb3,
	0x7f, 0x00, 0x7e, 0xc9, 0x92, 0x7f, 0xd0, 0x88, 0xee, 0x27, 0x93, 0xcb, 0x28, 0xea, 0xfc, 0x21,
	0x4d, 0xa8, 0x5d, 0x8d, 0xaf, 0x6f, 0x3a, 0xde, 0xe8, 0x1c, 0xda, 0x61, 0x99, 0x95, 0xa8, 0x8c,
	0x0a, 0x39, 0x86, 0xba, 0x5b, 0x46, 0x3a, 0x2b, 0x7b, 0x5d, 0x54, 0xba, 0x3b, 0xdf, 0x2e, 0x79,
	0xf2, 0x5d, 0xb2, 0xce, 0x3e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x58, 0xf0, 0xf8, 0x46, 0x72, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PricingServiceClient is the client API for PricingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PricingServiceClient interface {
	Price(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (*PriceResponse, error)
}

type pricingServiceClient struct {
	cc *grpc.ClientConn
}

func NewPricingServiceClient(cc *grpc.ClientConn) PricingServiceClient {
	return &pricingServiceClient{cc}
}

func (c *pricingServiceClient) Price(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (*PriceResponse, error) {
	out := new(PriceResponse)
	err := c.cc.Invoke(ctx, "/v1.PricingService/Price", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PricingServiceServer is the server API for PricingService service.
type PricingServiceServer interface {
	Price(context.Context, *PriceRequest) (*PriceResponse, error)
}

// UnimplementedPricingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPricingServiceServer struct {
}

func (*UnimplementedPricingServiceServer) Price(ctx context.Context, req *PriceRequest) (*PriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Price not implemented")
}

func RegisterPricingServiceServer(s *grpc.Server, srv PricingServiceServer) {
	s.RegisterService(&_PricingService_serviceDesc, srv)
}

func _PricingService_Price_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).Price(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PricingService/Price",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).Price(ctx, req.(*PriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PricingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.PricingService",
	HandlerType: (*PricingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Price",
			Handler:    _PricingService_Price_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pricing-service.proto",
}
